#!/bin/bash
######################################################################
#
# Set the GIT_SSH environment variable to this short script to ensure
# that the calling script won't ever prompt the user for a passphrase.
#
# Without this small wrapper around ssh, there is no way to prevent
# commands such as 'git clone' from prompting the user. As the import
# task is run in the background, the task would just stop and wait
# indefinitely if it were to wait for a user input. Unfortunately,
# the situation is likely to happen as users may fail to set the
# SSH key generated by the factory correctly to their git repository.
#
# The wrapper also takes care of disabling strict host key checking
# since we do not know anything about the remote server there's no
# human being around to validate its fingerprint.
#
# Usage:
#  GIT_SSH=./ssh-noprompt.sh git clone git@bitbucket.org:joshfire/foo.git
######################################################################
if [ -z "${GIT_SSH_TMPKEY}" ]
then
  ssh -i /dev/null -o IdentitiesOnly=yes -o BatchMode=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $@
else  
  ssh -i ${GIT_SSH_TMPKEY} -o IdentitiesOnly=yes -o BatchMode=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $@
fi